const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  // サービス一覧ページから全てのサービスURLを取得
  await page.goto('https://ledianclinic.jp/service/');
  const serviceLinks = await page.evaluate(() => {
    const links = Array.from(document.querySelectorAll('a[href*="/service/"]'));
    const serviceUrls = [];
    const seen = new Set();

    links.forEach(link => {
      const url = link.href;
      if (url.includes('/service/') && !url.endsWith('/service/') && !seen.has(url)) {
        seen.add(url);
        const match = url.match(/\/service\/([^\/]+)\/?$/);
        if (match) {
          serviceUrls.push({
            url: url,
            slug: decodeURIComponent(match[1])
          });
        }
      }
    });
    return serviceUrls;
  });

  console.error(`Found ${serviceLinks.length} services to scrape\n`);

  const allFaqs = [];

  for (const service of serviceLinks) {
    try {
      await page.goto(service.url, { timeout: 30000 });
      
      // FAQセクションを探す - 本番サイトの構造に合わせる
      const faqs = await page.evaluate(() => {
        const faqItems = [];
        
        // .faq-item 形式（本番サイトの構造）
        const items = document.querySelectorAll('.faq-item');
        items.forEach(item => {
          const questionEl = item.querySelector('.faq-item__q span, .faq-item__q');
          const answerEl = item.querySelector('.faq-item__a p, .faq-item__a');
          
          if (questionEl && answerEl) {
            const q = questionEl.textContent?.trim();
            const a = answerEl.textContent?.trim();
            if (q && a) {
              faqItems.push({ question: q, answer: a });
            }
          }
        });

        return faqItems;
      });

      if (faqs.length > 0) {
        console.error(`${service.slug}: ${faqs.length} FAQs found`);
        faqs.forEach((faq, i) => {
          allFaqs.push({
            slug: service.slug,
            question: faq.question,
            answer: faq.answer,
            sort_order: i
          });
        });
      } else {
        console.error(`${service.slug}: No FAQs`);
      }
    } catch (error) {
      console.error(`Error scraping ${service.slug}: ${error.message}`);
    }
  }

  console.error(`\n\n=== Total FAQs found: ${allFaqs.length} ===\n`);

  // SQL生成（1行で出力）
  console.log('-- SQL INSERT statements for service_faqs --');
  console.log('-- Generated by scripts/scrape_faqs.js --\n');
  
  allFaqs.forEach(faq => {
    const escapedQ = faq.question.replace(/'/g, "''").replace(/\n/g, ' ');
    const escapedA = faq.answer.replace(/'/g, "''").replace(/\n/g, ' ');
    const encodedSlug = encodeURIComponent(faq.slug).toLowerCase();
    console.log(`INSERT INTO service_faqs (id, service_content_id, question, answer, sort_order) SELECT lower(hex(randomblob(16))), sc.id, '${escapedQ}', '${escapedA}', ${faq.sort_order} FROM service_contents sc WHERE sc.slug = '${faq.slug}' OR sc.slug = '${encodedSlug}';`);
  });

  await browser.close();
})();
