const { chromium } = require('playwright');

// 欠損しているサービスのslugリスト
const missingSlugs = [
  'subcision',
  'thread-lift',
  '%e3%82%b7%e3%83%a7%e3%83%83%e3%83%94%e3%83%b3%e3%82%b0%e3%83%aa%e3%83%95%e3%83%88', // ショッピングリフト
  'roma-pink',
  'skin-boosting-injection' // 肌育注射
];

const serviceUrls = [
  { slug: 'subcision', url: 'https://ledianclinic.jp/service/subcision/' },
  { slug: 'thread-lift', url: 'https://ledianclinic.jp/service/thread-lift/' },
  { slug: '%e3%82%b7%e3%83%a7%e3%83%83%e3%83%94%e3%83%b3%e3%82%b0%e3%83%aa%e3%83%95%e3%83%88', url: 'https://ledianclinic.jp/service/%e3%82%b7%e3%83%a7%e3%83%83%e3%83%94%e3%83%b3%e3%82%b0%e3%83%aa%e3%83%95%e3%83%88/' },
  { slug: 'roma-pink', url: 'https://ledianclinic.jp/service/roma-pink/' },
  { slug: 'skin-boosting-injection', url: 'https://ledianclinic.jp/service/skin-boosting-injection/' }
];

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  console.log('-- SQL INSERT statements for service_overviews --');
  console.log('-- Generated by scripts/scrape_overviews.js --\n');

  for (const service of serviceUrls) {
    try {
      await page.goto(service.url, { timeout: 30000 });
      
      // 施術概要セクションからデータを抽出
      const overview = await page.evaluate(() => {
        const overviewHeading = Array.from(document.querySelectorAll('h2, h3')).find(h => 
          h.textContent.includes('施術概要') || h.textContent.includes('OVERVIEW')
        );
        
        if (!overviewHeading) return null;
        
        const section = overviewHeading.closest('section') || overviewHeading.parentElement?.parentElement?.parentElement;
        if (!section) return null;
        
        const rows = section.querySelectorAll('tbody tr');
        const data = {};
        
        rows.forEach(row => {
          const cells = row.querySelectorAll('td');
          if (cells.length >= 2) {
            const key = cells[0].textContent.trim();
            const value = cells[1].textContent.trim();
            data[key] = value;
          }
        });
        
        return data;
      });

      if (overview && Object.keys(overview).length > 0) {
        console.error(`${service.slug}: Overview found with ${Object.keys(overview).length} items`);
        
        const duration = (overview['施術時間'] || '').replace(/'/g, "''");
        const downtime = (overview['ダウンタイム'] || '').replace(/'/g, "''");
        const frequency = (overview['施術頻度'] || '').replace(/'/g, "''");
        const makeup = (overview['メイク'] || '').replace(/'/g, "''");
        const bathing = (overview['入浴'] || '').replace(/'/g, "''");
        const contraindications = (overview['禁忌'] || '').replace(/'/g, "''");
        
        console.log(`INSERT INTO service_overviews (id, service_content_id, duration, downtime, frequency, makeup, bathing, contraindications) SELECT lower(hex(randomblob(16))), sc.id, '${duration}', '${downtime}', '${frequency}', '${makeup}', '${bathing}', '${contraindications}' FROM service_contents sc WHERE sc.slug = '${service.slug}';`);
      } else {
        console.error(`${service.slug}: No overview found`);
      }
    } catch (error) {
      console.error(`Error scraping ${service.slug}: ${error.message}`);
    }
  }

  await browser.close();
})();

